### ISSUE TITLE
Impl. error

### ISSUE THREAD

**Issue by merlinarer** [explanare/ravel#1]
Hi, I find there is a Impl. difference between pyvene and raval in
https://github.com/explanare/ravel/blob/c19ef0f233eaf433e88c96d0dc676e9344fb8fda/src/methods/distributed_alignment_search.py#L25C1-L26C1

It should be:
```
output = base + torch.matmul(
        (rotated_source - rotated_base), self.rotate_layer.weight.T)
```

**Comment by explanare** [comment]
Yes, the interchange intervention line indeed differs by a transpose, but that's because there is actually another difference: the two implementations also initialize the rotation layer differently:

ravel: https://github.com/explanare/ravel/blob/main/src/methods/distributed_alignment_search.py#L13-L15
```python
    self.rotate_layer = torch.nn.utils.parametrizations.orthogonal(
        torch.nn.Linear(embed_dim,
                        kwargs["low_rank_dimension"],
                        bias=False))
```
pyvene: https://github.com/stanfordnlp/pyvene/blob/main/pyvene/models/layers.py#L41

```python
self.weight = torch.nn.Parameter(torch.empty(n, m), requires_grad=True)
```
